[workspace]
resolver = "2"
members = [
  "src/library/",
  "src/core",
  "src/webserver/",
  "src/app/",
  "src/inspector/",
  "src/tui/",
  "src/playhistoryimport",
  "src/ytimporter",
  "src/musicbrainz",
]
