[package]
name = "musiqlibrary"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
claxon = "0.4.3"
id3 = "1.0.1"
mp3-duration = "0.1.10"
mp4ameta = "0.11.0"
